import React, { useMemo, useState } from 'react';

const sections = [
  ['overview', '01. OVERVIEW'], ['how', '02. HOW IT WORKS'], ['onboarding', '03. CREATOR CONTEXT'],
  ['mind', '04. THE MIND'], ['memory', '05. MEMORY'], ['background', '06. BACKGROUND WORK'],
  ['briefing', '07. DECISION BRIEFING'], ['truth', '08. EVIDENCE & LIMITS'], ['faq', '09. FAQ'],
];

const lifecycle = [
  ['01 — OBJECTIVE', 'The creator defines the outcome GreenRoom should keep in view.'],
  ['02 — LIVE EVIDENCE', 'For the supported AI-video vertical, GreenRoom checks current first-party Adobe Blog evidence.'],
  ['03 — RELEVANT MEMORY', 'GreenRoom selects useful preferences, constraints, and prior decisions.'],
  ['04 — DECISION', 'The verified platform Mind evaluates the live evidence against the objective and Memory using the equipped Decision Skill.'],
  ['05 — PERSISTED BRIEFING', 'The run-specific result keeps its source, decision fields, and identity attached.'],
  ['06 — FEEDBACK', 'Creator feedback becomes context for later decisions without rewriting old results.'],
];

const faqs = [
  ['What is GreenRoom?', 'Persistent decision intelligence for solo creators. It remembers creator context, keeps an objective active, and returns concise decision briefings.'],
  ['How is it different from a normal chatbot?', 'GreenRoom is organized around durable context, immutable objective-bound runs, and feedback across sessions—not a single conversation.'],
  ['Does work continue after I leave?', 'When background execution is configured, the run persists independently of the open interface. The UI reports working, result ready, no relevant update, or run failed without inventing progress.'],
  ['Which platform Mind is verified?', 'Udophia at udophia@hellominds.ai, UUID 8208493e-f36b-1410-8466-00039ce7df11, is the only verified platform Mind.'],
  ['Is the current evidence live research?', 'Yes for the first supported AI-video objective. GreenRoom retrieves and validates first-party Adobe Blog metadata. Other creator domains truthfully report that no live provider exists yet. Historical demo briefings remain labeled simulated.'],
  ['What happens when execution fails?', 'The run is shown as failed. A timeout, missing reply, identity mismatch, or invalid response is never presented as a completed briefing.'],
];

function DocHead({ label, title }) { return <header className="docs-content-head"><span>{label}</span><h2>{title}</h2></header>; }

function SectionBody({ id }) {
  if (id === 'overview') return <><DocHead label="PRODUCT THESIS" title="Persistent decision intelligence for creators."/><p>GreenRoom helps solo creators carry goals, preferences, constraints, and prior decisions from one session to the next. It is not a chatbot or content generator. AI video is the first supported live vertical, not the scope of the product.</p><h3>Current live coverage</h3><p><strong>Domain:</strong> AI video tools and workflow<br/><strong>Provider:</strong> Adobe Blog</p><p>Writing, design, audio, publishing, growth, and other creator domains are roadmap work and truthfully return <strong>NO LIVE PROVIDER</strong> today.</p></>;
  if (id === 'how') return <><DocHead label="CORE LOOP" title="One thread through the work."/><div className="docs-lifecycle">{lifecycle.map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></>;
  if (id === 'onboarding') return <><DocHead label="CREATOR CONTEXT" title="Start with what should persist."/><p>Onboarding records the existing creator profile fields: name, niche, audience, preferred tone, primary goal, brand attributes, and topic constraints. This phase preserves that schema; its value should be validated against real personalization behavior.</p><p>Creator context can be reviewed from Memory, where additional preferences and feedback can be taught in human language.</p></>;
  if (id === 'mind') return <><DocHead label="VERIFIED PLATFORM IDENTITY" title="Udophia remains available without obscuring provenance."/><p>Udophia is the only verified platform Mind: <code>udophia@hellominds.ai</code>, UUID <code>8208493e-f36b-1410-8466-00039ce7df11</code>. The official Builder identity, conversation, SSE, and history integration remains in the product.</p><p>The normal live-evidence briefing is generated by the verified platform Mind (Udophia) using the equipped Decision Skill. GreenRoom orchestrates this asynchronously via background collection. When a verified reply arrives, the decision and provenance are persisted. If the Mind is latent or unavailable, the creator is shown a delayed state and can review the raw verified update directly.</p></>;
  if (id === 'memory') return <><DocHead label="PERSISTENT MEMORY" title="Useful context, carried forward."/><p>Memory includes creator profile facts, objectives, learned preferences, constraints, feedback, decision history, and briefing references. Relevant Memory is selected for a run; the complete creator profile remains durable.</p><p>For example, a saved preference such as <strong>“Prefer free or low-cost tools.”</strong> can influence a later tool-evaluation cycle when it is relevant. Selection does not rewrite earlier briefings.</p><div className="docs-flow">PROFILE + FEEDBACK <b>→</b> RELEVANT CONTEXT <b>→</b> OBJECTIVE-BOUND RUN <b>→</b> NEXT CYCLE</div></>;
  if (id === 'background') return <><DocHead label="HONEST LIFECYCLE" title="Leave the screen. Keep the thread."/><p>Production runs through the existing signed background worker and durable persistence. The creator-facing contract is intentionally simpler than the infrastructure:</p><div className="docs-state-row"><span>QUEUED</span><span>WORKING</span><span>RESULT READY</span><span>NO RELEVANT UPDATE</span><span>NO LIVE PROVIDER</span><span>RUN FAILED</span></div><p>Closing the lifecycle view does not cancel durable work. Waiting and prior briefings are never presented as a new result.</p></>;
  if (id === 'briefing') return <><DocHead label="DECISION BRIEFING" title="What deserves attention."/><p>Every completed item preserves the existing briefing contract and stays attached to its run and objective.</p><div className="docs-lifecycle"><article><h3>WHAT CHANGED</h3><p>The relevant finding.</p></article><article><h3>WHY IT MATTERS</h3><p>Its significance for this creator and objective.</p></article><article><h3>WHAT TO DO NEXT</h3><p>One practical next action.</p></article></div></>;
  if (id === 'truth') return <><DocHead label="LIVE EVIDENCE" title="Every current claim keeps its source."/><p>The supported AI-video lifecycle reads Adobe’s official Blog index, rejects malformed, future, stale, or weakly related items, and preserves the selected article URL and publication date.</p><ul><li>GreenRoom deterministically constructs only claims supported by the source metadata and objective match.</li><li>Historical simulated briefings remain labeled simulated and are never rewritten.</li><li>Minds reply latency remains a known limitation; if a response is delayed or fails, GreenRoom shows the raw verified update directly without fabricating a personalized response.</li></ul></>;
  return <><DocHead label="QUESTIONS" title="GreenRoom FAQ"/><div className="docs-faq">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></>;
}

export function DocsPage() {
  const [activeSection, setActiveSection] = useState('overview');
  const [search, setSearch] = useState('');
  const filtered = useMemo(() => sections.filter(([, title]) => title.toLowerCase().includes(search.toLowerCase())), [search]);
  return <div className="docs-page"><header className="docs-hero"><p>PRODUCT DOCUMENTATION</p><h1>GreenRoom, explained.</h1><span>The product model—from creator context to an honest, persisted decision briefing.</span></header><div className="docs-layout"><aside className="docs-nav"><label><span>SEARCH DOCUMENTATION</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search sections"/></label><nav>{filtered.map(([id, title]) => <button key={id} className={activeSection === id ? 'is-active' : ''} onClick={() => setActiveSection(id)}>{title}</button>)}</nav></aside><article className="docs-content"><SectionBody id={activeSection}/></article></div></div>;
}

export default DocsPage;
