import React from 'react';
import { motion } from 'framer-motion';
import { GreenroomCore } from '../components/mind/GreenroomCore';
import { soundFx } from '../lib/sound';
import { EvidenceGroundingMatrix } from '../components/evidence/EvidenceGroundingMatrix';

export function HomePage({
  memoryState,
  activeCards,
  mindsStatus,
  signals = [],
  onNavigate,
  onRunFullDemo,
  onOpenOnboarding,
  onOpenOfflineModal,
  isExecuting,
}) {
  const creatorName = memoryState?.creator_name || 'CREATOR';
  const niche = memoryState?.niche || 'Developer Tools & AI Automation';
  const learnedRules = memoryState?.learned_voice_rules || [];
  const memoryNodes = memoryState?.memory_nodes || [];
  const benchmarks = memoryState?.monetization_benchmarks || {};

  const scriptData = activeCards?.script;
  const isPunchy = scriptData?.is_punchy_voice || learnedRules.some((r) => r.toLowerCase().includes('punchy'));

  // Export Executive Briefing Document
  const handleExportBriefing = () => {
    soundFx.playSuccessChime();
    const dateStr = new Date().toISOString().split('T')[0];
    const content =
      `==================================================\n` +
      `GREENROOM PERSISTENT AI CHIEF OF STAFF\n` +
      `EXECUTIVE CREATOR BRIEFING — ${dateStr}\n` +
      `==================================================\n\n` +
      `CREATOR: ${creatorName.toUpperCase()}\n` +
      `NICHE: ${niche}\n` +
      `STATUS: Chief of Staff Engine Online & Monitoring\n\n` +
      `--------------------------------------------------\n` +
      `1. WHILE YOU WERE AWAY — SIGNALS & CONTEXT\n` +
      `--------------------------------------------------\n` +
      `• Audience Signal: Demand Spike (88% Positive Sentiment for beginner local code setup walkthroughs).\n` +
      `• Scout Trend: "Beginner AI Workflows & Automation" (Fit Score: 0.92, Volume: 145k/day).\n` +
      `• Business Match: TechBrand Inc. ($5,400 Pitch Brief, $45 CPM Target Benchmark).\n\n` +
      `--------------------------------------------------\n` +
      `2. GREENROOM'S STRATEGIC TAKE\n` +
      `--------------------------------------------------\n` +
      `Audience engagement is shifting heavily toward practical setup guides and direct open-source repositories.\n` +
      `Active Memory Rules: ${learnedRules.length} learned creator voice rules active.\n\n` +
      `--------------------------------------------------\n` +
      `3. RECOMMENDED CREATIVE DIRECTION\n` +
      `--------------------------------------------------\n` +
      `${scriptData?.script_concept || 'Script Concept: Beginner AI Workflows & Automation'}\n\n` +
      `==================================================\n` +
      `Generated by Greenroom Persistent AI Staff Engine\n`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Greenroom_Executive_Briefing_${dateStr}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const defaultSignals = [
    {
      id: 'sig_1',
      category: 'AUDIENCE SIGNAL',
      icon: 'radar',
      badge: '88% Sentiment',
      title: 'Audience Demand Spike',
      description: 'Viewers requesting beginner local agent setup guides and direct GitHub repository links.',
    },
    {
      id: 'sig_2',
      category: 'SCOUT TREND',
      icon: 'trending_up',
      badge: 'Fit Score: 0.92',
      title: 'Niche Trend Flagged',
      description: '"Beginner AI Workflows & Automation" flagged as high-fit topic while clickbait was filtered out.',
    },
    {
      id: 'sig_3',
      category: 'BUSINESS MATCH',
      icon: 'monetization_on',
      badge: `$${benchmarks.cpm_target || 45} CPM`,
      title: 'Sponsorship Deal Draft',
      description: `Business Mind scored TechBrand Inc. at 89% match size and drafted a $${benchmarks.minimum_deal_size || 5000} pitch brief.`,
    },
  ];

  const activeSignals = signals && signals.length > 0 ? signals.map((s, idx) => ({
    id: s.signal_id || `sig_${idx}`,
    category: (s.source || 'LIVE SIGNAL').toUpperCase(),
    icon: s.type === 'trend' ? 'trending_up' : s.type === 'deal' ? 'monetization_on' : 'radar',
    badge: s.fit_score ? `Fit: ${s.fit_score}` : s.sentiment ? `${(s.sentiment * 100).toFixed(0)}% Sentiment` : 'VERIFIED',
    title: s.title || s.trend_name || 'Audience Signal Item',
    description: s.summary || s.description || 'Live audience signal ingested from creator stream.',
  })) : defaultSignals;

  return (
    <div className="flex-1 flex flex-col min-w-0 pb-16 text-white font-sans space-y-8 max-w-container-max mx-auto px-6 md:px-10 pt-4">
      
      {/* 1. HERO SECTION: THE LIVING MIND CORE PROMINENTLY FIRST */}
      <section className="noir-card p-6 md:p-8 bg-[#0e1014]/90 border border-primary-fixed/30 shadow-2xl overflow-hidden relative">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
          
          {/* Left Column: Greeting, Channel Context & Action Buttons (7 Cols) */}
          <div className="lg:col-span-7 space-y-5 z-10">
            <div className="space-y-2">
              <div className="flex items-center gap-2.5">
                <span className="w-2.5 h-2.5 rounded-full bg-primary-fixed animate-pulse shadow-[0_0_10px_#72ff70]" />
                <span className="font-mono text-primary-fixed uppercase tracking-widest text-xs font-bold bg-[#142616] px-3 py-0.5 rounded border border-[#234d28]">
                  SYSTEM ONLINE • GREENROOM CORE MIND
                </span>
              </div>

              <h1 className="text-2xl sm:text-3xl md:text-4xl font-display font-bold text-white tracking-tight leading-tight">
                GOOD MORNING, {creatorName.toUpperCase()}.{' '}
                <span className="text-primary-fixed block md:inline drop-shadow-[0_0_15px_rgba(114,255,112,0.3)]">
                  Greenroom is active.
                </span>
              </h1>

              <p className="text-xs md:text-sm font-sans text-zinc-200 border-l-2 border-primary-fixed pl-3 py-1 leading-relaxed font-medium">
                Autonomous AI Chief of Staff monitoring signals for your <strong className="text-primary-fixed">{niche}</strong> channel and synthesizing strategic creator directions.
              </p>

              {/* Core Product Thesis Banner */}
              <div className="p-3.5 bg-[#142616] border border-[#234d28] rounded-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 font-mono text-xs shadow-lg mt-3">
                <div className="flex items-center gap-2">
                  <span className="material-symbols-outlined text-primary-fixed text-lg">auto_awesome</span>
                  <span className="text-white font-bold tracking-tight">PRODUCT THESIS:</span>
                </div>
                <div className="flex flex-wrap items-center gap-2 text-[11px] font-bold">
                  <span className="text-primary-fixed bg-[#0a0c0e] px-2.5 py-1 rounded border border-emerald-800/80 shadow-[0_0_8px_rgba(114,255,112,0.15)]">
                    GREENROOM WORKS WHILE YOU WORK.
                  </span>
                  <span className="text-zinc-500 hidden sm:inline">•</span>
                  <span className="text-emerald-300 bg-[#0a0c0e] px-2.5 py-1 rounded border border-emerald-800/80 shadow-[0_0_8px_rgba(114,255,112,0.15)]">
                    GREENROOM REMEMBERS WHY.
                  </span>
                </div>
              </div>
            </div>

            {/* Quick Action Buttons */}
            <div className="flex flex-wrap items-center gap-3 pt-2">
              {onOpenOnboarding && (
                <button
                  onClick={onOpenOnboarding}
                  className="px-4 py-2.5 bg-[#142616] border border-[#234d28] hover:border-primary-fixed/60 text-primary-fixed text-xs font-mono font-bold transition flex items-center gap-2 rounded shadow-md"
                >
                  <span className="material-symbols-outlined text-base">edit_note</span>
                  <span>Edit Profile</span>
                </button>
              )}

              <button
                onClick={handleExportBriefing}
                className="px-4 py-2.5 bg-[#111115] border border-outline-variant hover:border-primary-fixed/60 text-zinc-200 hover:text-white text-xs font-mono font-bold transition flex items-center gap-2 rounded shadow-md"
                title="Download Executive Briefing Document"
              >
                <span className="material-symbols-outlined text-base text-primary-fixed">download</span>
                <span>Export Briefing</span>
              </button>

              {onOpenOfflineModal && (
                <button
                  onClick={() => {
                    soundFx.playSynapsePulse();
                    onOpenOfflineModal();
                  }}
                  className="px-4 py-2.5 bg-emerald-950/80 border border-emerald-500/60 hover:border-primary-fixed text-emerald-300 hover:text-white text-xs font-mono font-bold transition flex items-center gap-2 rounded shadow-lg shadow-emerald-950/40"
                  title="Prove the complete offline chain: QStash Queue -> Minds SDK -> Durable Storage -> Briefing Delivery"
                >
                  <span className="material-symbols-outlined text-base text-primary-fixed animate-pulse">cloud_done</span>
                  <span>Prove Offline Story</span>
                </button>
              )}

              <button
                onClick={() => {
                  soundFx.playSynapsePulse();
                  onRunFullDemo();
                }}
                disabled={isExecuting}
                className="px-5 py-2.5 bg-primary-container text-on-primary-container text-xs font-sans font-bold hover:bg-primary-fixed-dim transition-colors flex items-center gap-2 rounded disabled:opacity-50 shadow-lg shadow-primary-container/20 whitespace-nowrap"
              >
                <span className="material-symbols-outlined text-base font-bold">play_arrow</span>
                <span>Run Agent Briefing</span>
              </button>
            </div>
          </div>

          {/* Right Column: LIVING MIND CORE VISUALIZER (5 Cols) */}
          <div className="lg:col-span-5 flex justify-center z-10">
            <GreenroomCore
              stateName={isExecuting ? 'COLLABORATING' : 'IDLE'}
              subtitle="Autonomous Chief of Staff Engine managing persistent creator intelligence."
            />
          </div>
        </div>
      </section>

      {/* 1. WHAT DID GREENROOM LEARN? (PERSISTED CREATOR CONTEXT) */}
      {learnedRules.length > 0 && (
        <div className="p-4 bg-[#142616]/60 border border-[#234d28] rounded-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4 font-mono text-xs shadow-lg">
          <div className="flex items-center gap-3">
            <span className="material-symbols-outlined text-primary-fixed text-2xl">psychology</span>
            <div>
              <span className="text-primary-fixed font-bold uppercase block text-[10px] tracking-wider">
                1. WHAT DID GREENROOM LEARN? (PERSISTED VOICE RULES)
              </span>
              <span className="text-zinc-200 font-medium">
                Active Creator Constraint: <strong className="text-white">"{learnedRules[learnedRules.length - 1]}"</strong>
              </span>
            </div>
          </div>
          <div className="flex items-center gap-3">
            {onOpenMemoryProofModal && (
              <button
                onClick={() => {
                  soundFx.playSynapsePulse();
                  onOpenMemoryProofModal();
                }}
                className="px-3 py-1.5 bg-emerald-950/80 border border-emerald-500/60 hover:border-primary-fixed text-emerald-300 hover:text-white font-bold text-xs rounded flex items-center gap-1 transition shadow-sm"
              >
                <span className="material-symbols-outlined text-sm text-primary-fixed">psychology</span>
                <span>Prove Memory Adaptation</span>
              </button>
            )}
            <button
              onClick={() => onNavigate('memory')}
              className="text-primary-fixed hover:underline font-bold text-xs flex items-center gap-1 whitespace-nowrap"
            >
              Inspect DNA ({learnedRules.length} Rules) →
            </button>
          </div>
        </div>
      )}

      {/* 2. WHAT DID GREENROOM DISCOVER? (SIGNALS STREAM) */}
      <div className="space-y-4">
        <h2 className="text-xs font-mono text-primary-fixed uppercase tracking-widest flex items-center gap-2 font-bold">
          <span className="w-3 h-[2px] bg-primary-fixed block" />
          2. WHAT DID GREENROOM DISCOVER? (SCOUT + COMMUNITY + BUSINESS SIGNALS)
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
          {activeSignals.map((sig, index) => (
            <motion.div
              key={sig.id || index}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: index * 0.05 }}
              onClick={() => soundFx.playSynapsePulse()}
              className="noir-card p-5 flex flex-col justify-between space-y-4 cursor-pointer group"
            >
              <div className="flex justify-between items-start">
                <span className="material-symbols-outlined text-primary-fixed group-hover:scale-110 transition-transform text-2xl">
                  {sig.icon}
                </span>
                <span className="font-mono text-xs text-primary-fixed font-bold bg-[#142616] px-2.5 py-0.5 rounded border border-[#234d28]">
                  {sig.badge}
                </span>
              </div>
              <div className="space-y-1">
                <span className="font-mono text-[10px] text-zinc-400 font-bold uppercase tracking-wider block">{sig.category}</span>
                <h3 className="text-base font-sans font-bold text-white group-hover:text-primary-fixed transition-colors">
                  {sig.title}
                </h3>
                <p className="text-xs font-sans text-zinc-300 leading-relaxed font-medium">
                  {sig.description}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* FIRST-CLASS EVIDENCE MATRIX */}
      <EvidenceGroundingMatrix
        memoryState={memoryState}
        scriptData={scriptData}
        pitchData={activeCards?.pitch}
      />

      {/* 3 & 4. WHY DOES GREENROOM RECOMMEND THIS? & WHAT CAN GREENROOM DO? */}
      <div className="noir-card p-6 flex flex-col space-y-6 border-l-4 border-l-primary-fixed">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-3 border-b border-outline-variant/60 pb-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="material-symbols-outlined text-primary-fixed text-base">priority_high</span>
              <span className="font-mono text-primary-fixed text-xs uppercase tracking-wider font-bold">
                3. WHY DOES GREENROOM RECOMMEND THIS? • STRATEGIC DIRECTIVE
              </span>
              {isPunchy && (
                <span className="font-mono text-[10px] font-bold text-amber-300 bg-amber-950 border border-amber-800 px-2 py-0.5 rounded-full flex items-center gap-1 animate-pulse">
                  Punchy Voice Active
                </span>
              )}
            </div>

            <h2 className="text-xl md:text-2xl font-display font-bold text-white">
              Script Concept: Beginner AI Workflows & Automation
            </h2>
          </div>

          {/* 4. WHAT CAN GREENROOM DO? (ACTION TRIGGER) */}
          <div className="space-y-1">
            <span className="font-mono text-[10px] text-zinc-400 font-bold uppercase block text-right">
              4. WHAT CAN GREENROOM DO?
            </span>
            <button
              onClick={() => {
                soundFx.playSynapsePulse();
                onNavigate('actions');
              }}
              className="bg-primary-container text-on-primary-container text-xs font-sans font-bold py-3 px-5 hover:bg-primary-fixed-dim transition-colors flex justify-center items-center gap-2 rounded disabled:opacity-50 shadow-lg shadow-primary-container/20 whitespace-nowrap"
            >
              <span>Execute Actions & Pitch Brief</span>
              <span className="material-symbols-outlined text-base font-bold">arrow_forward</span>
            </button>
          </div>
        </div>

        {/* Transparent Grounding Breakdown */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3 font-mono text-xs">
          <div className="p-2.5 bg-[#0a0c0e] rounded border border-outline-variant space-y-1">
            <span className="text-primary-fixed font-bold block text-[10px] uppercase">WHY CHOSEN</span>
            <span className="text-zinc-200">Matches beginner audience retention profile.</span>
          </div>
          <div className="p-2.5 bg-[#0a0c0e] rounded border border-outline-variant space-y-1">
            <span className="text-cyan-400 font-bold block text-[10px] uppercase">EVIDENCE CITATION</span>
            <span className="text-zinc-200">Scout Market Volume + Community Viewer Demand.</span>
          </div>
          <div className="p-2.5 bg-[#0a0c0e] rounded border border-outline-variant space-y-1">
            <span className="text-amber-400 font-bold block text-[10px] uppercase">PERSISTED MEMORY RULE</span>
            <span className="text-zinc-200">{learnedRules[learnedRules.length - 1] || 'Default voice parameters'}</span>
          </div>
          <div className="p-2.5 bg-[#0a0c0e] rounded border border-outline-variant space-y-1">
            <span className="text-emerald-400 font-bold block text-[10px] uppercase">CONFIDENCE SCORE</span>
            <span className="text-primary-fixed font-bold">95% Alignment (Multi-Mind Verified)</span>
          </div>
        </div>

        {/* Script Content Preview */}
        <div className="p-4 bg-[#0e0e11] rounded border border-outline-variant font-mono text-xs text-zinc-200 leading-relaxed whitespace-pre-wrap max-h-48 overflow-y-auto shadow-inner">
          {scriptData?.script_concept || (
            `RECOMMENDED SCRIPT CONCEPT: Beginner AI Workflows & Automation\n\n` +
            `[HOOK - 0:00-0:15]\n` +
            `Stop wasting hours configuring complex local pipelines. Here are the 3 setup steps to launch your custom agent today.\n\n` +
            `[EXECUTION WALKTHROUGH - 0:15-2:30]\n` +
            `Step 1: Clone repository. Step 2: Set .env API key. Step 3: Execute python workflow script.\n\n` +
            `[CTA & SPONSOR INTEGRATION]\n` +
            `Check out the repo link below and TechBrand Inc. for native dev keys.`
          )}
        </div>
      </div>

      {/* 5. WHAT DID IT LEARN FROM MY DECISION? (LEARNING LOOP) */}
      <div className="noir-card p-6 space-y-4">
        <div className="space-y-2">
          <h2 className="text-xs font-mono text-primary-fixed uppercase tracking-widest flex items-center gap-2 font-bold">
            <span className="w-3 h-[2px] bg-primary-fixed block" />
            5. WHAT DID IT LEARN FROM MY DECISION? (CONTINUOUS FEEDBACK LOOP)
          </h2>

          <div className="text-lg md:text-xl font-display font-bold text-white leading-snug">
            Every rejection or approval extracts rules that persist across browser reloads.
          </div>

          <p className="text-xs md:text-sm font-sans text-zinc-200 leading-relaxed font-medium">
            When you approve a pitch or reject a clickbait concept on the Actions page, Greenroom extracts constraint rules and persists them into <strong className="text-primary-fixed">creator_profile.json</strong> to ensure future recommendations adapt to your preference.
          </p>
        </div>

        <div className="pt-3 border-t border-outline-variant/60 flex items-center justify-between font-mono text-xs">
          <span className="text-zinc-300 font-bold">
            {learnedRules.length} learned rules active in creator memory matrix
          </span>
          <button
            onClick={() => {
              soundFx.playSynapsePulse();
              onNavigate('actions');
            }}
            className="text-primary-fixed hover:underline font-bold text-xs flex items-center gap-1"
          >
            Go to Actions & Teach Greenroom →
          </button>
        </div>
      </div>

    </div>
  );
}

export default HomePage;
