import React, { useMemo, useState } from 'react';
import { GreenroomCore } from '../components/mind/GreenroomCore';
import { getDisplayMemories } from '../lib/memoryPresentation';

const clean = (v = '') => String(v).replace(/ScoutMind detected/i, 'Greenroom found').replaceAll('_', ' ');
const process = [['01','REMEMBER','Holds the creator context that makes the next decision specific.'],['02','WATCH','Keeps the current objective in view while you are away.'],['03','INTERPRET','Reads new signal against persistent creator context.'],['04','RETURN','Ranks what matters and makes the next action clear.']];

export function HomePage({ memoryState, onNavigate, onOpenOfflineModal, onCreateObjective, onRunObjective, isExecuting }) {
  const [editing, setEditing] = useState(false); const [title, setTitle] = useState(''); const [details, setDetails] = useState('');
  const objective = memoryState?.creator_objectives?.[0]; const briefing = memoryState?.latest_briefing; const items = Array.isArray(briefing?.items) ? briefing.items.slice(0,3) : [];
  const memories = useMemo(() => getDisplayMemories(memoryState).slice(0,3), [memoryState]);
  const runStatus = memoryState?.latest_offline_run?.status;
  const rawState = runStatus === 'FAILED' ? 'RUN FAILED' : ['QUEUED','RUNNING','SUBMITTING','WAITING_FOR_MINDS'].includes(runStatus) || objective?.status === 'RUNNING' ? 'WORKING' : items.length ? 'RESULT READY' : objective ? 'READY' : 'NO OBJECTIVE';
  const save = async e => { e.preventDefault(); if (!title.trim()) return; await onCreateObjective(title.trim(), details.trim()); setEditing(false); setTitle(''); setDetails(''); };
  return <div className="manus-home">
    <section className="new-hero"><div className="hero-intro"><p className="hero-overline">GREENROOM</p><h1>Persistent decision intelligence <em>for creators.</em></h1><p>Tell GreenRoom what you’re working toward. It remembers what matters to you, works in the background, and brings back the decisions worth your attention.</p><div className="hero-actions"><button className="hero-primary" onClick={() => setEditing(true)}>{objective ? 'Update objective' : 'Set an objective'} ↗</button><button className="hero-secondary" onClick={() => document.getElementById('how-it-works')?.scrollIntoView({behavior:'smooth'})}>See how it works ↘</button></div><div className="home-status-ribbon"><div><span>Objective</span><strong>{objective ? 'HELD' : 'WAITING'}</strong><p>{objective?.title || 'Set the outcome GreenRoom should keep in view.'}</p></div><div><span>Status</span><strong>{rawState}</strong><p>{rawState === 'WORKING' ? 'You can leave this screen. GreenRoom will hold the work.' : rawState === 'RUN FAILED' ? 'This run did not complete. No stale result has replaced it.' : rawState === 'RESULT READY' ? 'A completed, persisted briefing is ready.' : 'GreenRoom is ready when you are.'}</p></div><div><span>Memory</span><strong>{String(memories.length).padStart(2,'0')}</strong><p>{memories.length ? 'Creator context is available for the next decision.' : 'No creator preferences saved yet.'}</p></div></div></div></section>
    {editing && <section className="objective-editor"><form onSubmit={save}><p>SET THE THREAD</p><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="What should Greenroom accomplish?" autoFocus required/><input value={details} onChange={e=>setDetails(e.target.value)} placeholder="Constraints, timing, or target"/><div><button type="button" onClick={()=>setEditing(false)}>Cancel</button><button disabled={isExecuting}>Save objective</button></div></form></section>}
    <section className="story-section remember-story" id="how-it-works"><div className="story-heading"><p>01 — REMEMBER</p><h2>Context that <em>stays.</em></h2><p className="section-support">Greenroom keeps the useful parts of your context close to the next decision.</p></div><div className="memory-composition"><div className="memory-photo-frame"><img src="/assets/greenroom-creator-night.png" alt="Creator at work"/><img src="/assets/greenroom-living-network.png" alt=""/><span>CREATOR CONTEXT</span></div><div className="memory-fact"><p>CURRENT OBJECTIVE</p><strong>{objective?.title || 'Set the work you want Greenroom to keep in view.'}</strong><button onClick={()=>setEditing(true)}>{objective ? 'Edit objective' : 'Set an objective'} ↗</button></div><div className="memory-index">{String(memories.length).padStart(2,'0')} MEMORIES AVAILABLE</div></div><aside className="remembered-context"><div className="context-head"><span>REMEMBERED CONTEXT</span><button onClick={()=>onNavigate('memory')}>VIEW FULL MEMORY ↗</button></div>{memories.length ? <ul>{memories.map((m,i)=><li key={i}><span>0{i+1}</span><p>{clean(m)}</p></li>)}</ul> : <div className="capability-grid"><article><span>CREATOR PREFERENCES</span><p>How you prefer to work and decide.</p></article><article><span>ACTIVE OBJECTIVES</span><p>The outcomes Greenroom should keep in view.</p></article><article><span>LEARNED RULES</span><p>Repeated instructions that become useful context.</p></article><article><span>USEFUL HISTORY</span><p>Prior context that makes a later return clearer.</p></article></div>}</aside></section>
    <section className="process-story"><div className="process-heading"><p>HOW GREENROOM WORKS</p><h2>One thread through the work.</h2></div><div className="process-strip">{process.map(x=><article key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
    <section className="story-section work-story"><div className="work-visual"><img src="/assets/greenroom-living-network.png" alt=""/><GreenroomCore stateName={rawState}/><div className="work-caption"><span>THE MIND</span><strong>{rawState}</strong></div></div><div className="story-heading work-copy"><p>02 — WORK</p><h2>Present even when <em>you are not.</em></h2><p>Greenroom keeps the objective, makes sense of the signal, and holds the work until you return.</p><button className="inline-edit" disabled={!objective || isExecuting} onClick={onOpenOfflineModal}>Work while I’m away ↗</button></div></section>
    <section className="creator-away-story"><img src="/assets/greenroom-away-workspace.png" alt="Workspace after the creator leaves"/><div><p>CREATOR CONTINUITY</p><h2>You step away.<br/><em>The thread doesn’t.</em></h2><span>Greenroom maintains the objective and the context around it, so a useful return has somewhere to land.</span></div></section>
    <section className="return-story"><div className="return-intro"><p>03 — RETURN</p><h2>You were away.<br/><em>Greenroom found this.</em></h2></div>{items.length ? <div className="ranked-return">{items.map((item,i)=><article className={i===0?'is-first':''} key={item.id || item.title}><span>0{i+1}</span><div><p>{item.category || item.priority || 'OPPORTUNITY'}</p><h3>{item.title}</h3><dl><div><dt>WHY IT MATTERS</dt><dd>{clean(item.why_it_matters || 'Relevance supplied by the completed briefing.')}</dd></div><div><dt>NEXT ACTION</dt><dd>{item.recommended_action || 'Review this opportunity.'}</dd></div></dl></div></article>)}</div> : <div className="return-empty"><img src="/assets/greenroom-away-workspace.png" alt="Empty workspace"/><div><p>NO BRIEFING HAS RETURNED YET.</p><span>Set an objective, then let Greenroom work while you are away. Ranked results appear only after a completed run.</span></div></div>}</section>
    <section className="agent-story"><img src="/assets/greenroom-living-network.png" alt=""/><div className="agent-heading"><p>THE GREENROOM LOOP</p><h2>Three parts.<br/><em>One useful return.</em></h2></div><div className="agent-columns"><article><span>01</span><h3>SIGNAL</h3><p>Relevant input tied to the objective.</p></article><article><span>02</span><h3>CONTEXT</h3><p>Persistent creator memory shapes the decision.</p></article><article><span>03</span><h3>RETURN</h3><p>What changed, why it matters, and what to do next.</p></article></div></section>
    <section className="closing-story"><div><p>GREENROOM REMEMBERS</p><h2>Built to keep <em>the thread.</em></h2></div><div className="closing-links">{objective&&<button disabled={isExecuting} onClick={()=>onRunObjective(objective.id)}>Run objective ↗</button>}<button onClick={()=>setEditing(true)}>Set an objective ↗</button><button onClick={()=>onNavigate('memory')}>View Memory ↗</button><button onClick={()=>onNavigate('intelligence')}>Open Intelligence ↗</button></div></section>
  </div>;
}
export default HomePage;
